### ISSUE TITLE
Snakemake pipeline failed in Medaka

### ISSUE THREAD

**Issue by DuttaAnik** [pmenzel/ont-assembly-snake#17]
Hello,
Thank you for developing this super useful pipeline. I have two isolates of Agrobacterium species sequenced with ONT. After basecalling, I got 2.2Gb data for one isolate AT1, and 1.2 Gb data for the other isolate AT2. I ran the snakemake pipeline after creating the following folders:
```
cd assemblies/
mkdir AT51_flye+racon2+medaka
mkdir AT51+filtlongMB500_flye+racon2+medaka
```
The pipeline ran successfully and I got two fasta files one with Flye and the other after FiltlongMB500, both are 5.5 Mb and 5.3Mb, which correlates nicely with the reference genome size.

Then, I ran the same pipeline for the second isolate AT2, which gave me the following errors:
```
localrule medaka:
    input: assemblies/AT52+filtlongMB500_flye+racon2/output.fa, fastq-ont/AT52+filtlongMB500.fastq
    output: assemblies/AT52+filtlongMB500_flye+racon2+medaka/output.fa, assemblies/AT52+filtlongMB500_flye+racon2+medaka.fa
    log: assemblies/AT52+filtlongMB500_flye+racon2+medaka/log.txt
    jobid: 4
    benchmark: benchmark/AT52+filtlongMB500_flye+racon2+medaka.txt
    reason: Missing output files: assemblies/AT52+filtlongMB500_flye+racon2+medaka/output.fa, assemblies/AT52+filtlongMB500_flye+racon2+medaka.fa; Input files updated by another job: assemblies/AT52+filtlongMB500_flye+racon2/output.fa, fastq-ont/AT52+filtlongMB500.fastq
    wildcards: sample=AT52+filtlongMB500, assembly=flye+racon2
    threads: 5
    resources: tmpdir=/tmp, mem_mb=12000, mem_mib=11445

Activating conda environment: .snakemake/conda/1cbac47b5f6eedc5f9215003373f1837_
[Wed Jun 26 10:24:26 2024]
Error in rule medaka:
    jobid: 4
    input: assemblies/AT52+filtlongMB500_flye+racon2/output.fa, fastq-ont/AT52+filtlongMB500.fastq
    output: assemblies/AT52+filtlongMB500_flye+racon2+medaka/output.fa, assemblies/AT52+filtlongMB500_flye+racon2+medaka.fa
    log: assemblies/AT52+filtlongMB500_flye+racon2+medaka/log.txt (check log file(s) for error details)
    conda-env: /media/rd/Volume/MinIONdata/20240521_AT52/20240521_AT52/no_sample/20240521_1055_MN40069_AQX333_a91bd45c/Analyis/.snakemake/conda/1cbac47b5f6eedc5f9215003373f1837_
    shell:

        medaka_consensus -f -i fastq-ont/AT52+filtlongMB500.fastq -d assemblies/AT52+filtlongMB500_flye+racon2/output.fa -o assemblies/AT52+filtlongMB500_flye+racon2+medaka -t 5 -m r941_min_high_g351 >assemblies/AT52+filtlongMB500_flye+racon2+medaka/log.txt 2>&1
        mv assemblies/AT52+filtlongMB500_flye+racon2+medaka/consensus.fasta assemblies/AT52+filtlongMB500_flye+racon2+medaka/output.fa
        ln -sr assemblies/AT52+filtlongMB500_flye+racon2+medaka/output.fa assemblies/AT52+filtlongMB500_flye+racon2+medaka.fa

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-06-26T095729.187212.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```
**Can you please tell me what is going on with Medaka? How can I overcome this error?**

This is the command that I executed `snakemake -s /media/rd/Volume/ont-assembly-snake/Snakefile --use-conda --cores 20 --config medaka_model=r941_min_high_g351 filtlong_min_read_length=500`

**I have another question: which FASTA file is the final genome assembly of interest and should be used for downstream analysis?**

**Comment by pmenzel** [comment]
Hi,

it's hard to say what went wrong with Medaka here. 
You can have a look in the log files of the failed rules, e.g. `assemblies/AT52+filtlongMB500_flye+racon2+medaka/log.txt`.

Also make sure to use the latest version of the Pipeline from Github.

Note that you should not run snakemake from within the `assemblies/` folder.

Re your 2nd question, the final assembly of each step is in the output.fa file in each subfolder, which is symlinked as a fasta file in the `assemblies/` folder, e.g. ` AT52_flye+racon2.fa -> AT52_flye+racon2/output.fa`

**Comment by DuttaAnik** [comment]
Hello, 
I did not run the pipeline from the assemblies directory. The pipeline as a whole worked but only the medaka did not work. Also, I am using the latest version as I just cloned the current git repository.
